using RGB.NET.Core;

namespace KeychronLegacyLighting.RGB.NET;

/// <summary>
/// Contains mappings for <see cref="LedId"/> to <see cref="CorsairLedId"/>.
/// </summary>
internal static class LedMappings
{
    public static LedMapping<int> K2 { get; } = new()
    {
        { LedId.Keyboard_Escape, 0 },
        { LedId.Keyboard_F1, 6 },
        { LedId.Keyboard_F2, 9 },
        { LedId.Keyboard_F3, 15 },
        { LedId.Keyboard_F4, 20 },
        { LedId.Keyboard_F5, 25 },
        { LedId.Keyboard_F6, 30 },
        { LedId.Keyboard_F7, 36 },
        { LedId.Keyboard_F8, 41 },
        { LedId.Keyboard_F9, 46 },
        { LedId.Keyboard_F10, 51 },
        { LedId.Keyboard_F11, 57 },
        { LedId.Keyboard_GraveAccentAndTilde, 1 },
        { LedId.Keyboard_1, 7 },
        { LedId.Keyboard_2, 10 },
        { LedId.Keyboard_3, 16 },
        { LedId.Keyboard_4, 21 },
        { LedId.Keyboard_5, 26 },
        { LedId.Keyboard_6, 31 },
        { LedId.Keyboard_7, 37 },
        { LedId.Keyboard_8, 42 },
        { LedId.Keyboard_9, 47 },
        { LedId.Keyboard_0, 52 },
        { LedId.Keyboard_MinusAndUnderscore, 58 },
        { LedId.Keyboard_Tab, 2 },
        { LedId.Keyboard_Q, 11 },
        { LedId.Keyboard_W, 17 },
        { LedId.Keyboard_E, 22 },
        { LedId.Keyboard_R, 27 },
        { LedId.Keyboard_T, 32 },
        { LedId.Keyboard_Y, 38 },
        { LedId.Keyboard_U, 43 },
        { LedId.Keyboard_I, 48 },
        { LedId.Keyboard_O, 53 },
        { LedId.Keyboard_P, 59 },
        { LedId.Keyboard_BracketLeft, 65 },
        { LedId.Keyboard_CapsLock, 3 },
        { LedId.Keyboard_A, 12 },
        { LedId.Keyboard_S, 18 },
        { LedId.Keyboard_D, 23 },
        { LedId.Keyboard_F, 28 },
        { LedId.Keyboard_G, 33 },
        { LedId.Keyboard_H, 39 },
        { LedId.Keyboard_J, 44 },
        { LedId.Keyboard_K, 49 },
        { LedId.Keyboard_L, 54 },
        { LedId.Keyboard_SemicolonAndColon, 60},
        { LedId.Keyboard_ApostropheAndDoubleQuote, 66 },
        { LedId.Keyboard_LeftShift, 4 },
        { LedId.Keyboard_Z, 13 },
        { LedId.Keyboard_X, 19 },
        { LedId.Keyboard_C, 24 },
        { LedId.Keyboard_V, 29 },
        { LedId.Keyboard_B, 34 },
        { LedId.Keyboard_N, 40 },
        { LedId.Keyboard_M, 45 },
        { LedId.Keyboard_CommaAndLessThan, 50 },
        { LedId.Keyboard_PeriodAndBiggerThan, 55 },
        { LedId.Keyboard_SlashAndQuestionMark, 61 },
        { LedId.Keyboard_LeftCtrl,  5},
        { LedId.Keyboard_LeftGui, 8 },
        { LedId.Keyboard_LeftAlt, 14 },
        { LedId.Keyboard_Space, 35 },
        { LedId.Keyboard_RightAlt, 56 },
        { LedId.Keyboard_F12, 63 },
        { LedId.Keyboard_PrintScreen, 69 },
        { LedId.Keyboard_Home, 81 },
        { LedId.Keyboard_PageUp, 79 },
        { LedId.Keyboard_BracketRight, 71 },
        { LedId.Keyboard_Backslash, 74 },
        { LedId.Keyboard_Enter, 75 },
        { LedId.Keyboard_EqualsAndPlus, 64 },
        { LedId.Keyboard_Backspace, 70 },
        { LedId.Keyboard_Delete, 73 },
        { LedId.Keyboard_End, 82 },
        { LedId.Keyboard_PageDown, 80 },
        { LedId.Keyboard_RightShift, 67 },
        { LedId.Keyboard_RightCtrl, 68 },
        { LedId.Keyboard_ArrowUp, 76 },
        { LedId.Keyboard_ArrowLeft, 72 },
        { LedId.Keyboard_ArrowDown, 77 },
        { LedId.Keyboard_ArrowRight, 83 },
        { LedId.Keyboard_LedProgramming, 78 },
        { LedId.Keyboard_Function, 62 },
    };
}